"$schema" = 'https://starship.rs/config-schema.json'

palette = "everforest"
add_newline = false

format = """
[](orange)\
$os\
$username\
[](bg:yellow fg:orange)\
$directory\
[](fg:yellow bg:aqua)\
$git_branch\
$git_status\
$git_state\
[](fg:aqua bg:blue)\
$python\
[](fg:blue bg:bg3)\
$kubernetes\
[](fg:bg3 bg:bg1)\
$cmd_duration\
[](fg:bg1)\
$line_break$character"""

[os]
disabled = false
style = "bg:orange fg:bg1"
format = "[ $symbol]($style)"

[os.symbols]
Macos = ""

[username]
show_always = true
style_user = "bg:orange fg:bg1"
style_root = "bg:orange fg:bg1"
format = '[ $user ]($style)'

[directory]
style = "fg:bg1 bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:aqua fg:bg1"
format = '[[ $symbol $branch ](fg:bg1 bg:aqua)]($style)'

[git_status]
style = "bg:aqua fg:bg1"
format = '[[($all_status$ahead_behind )](fg:bg1 bg:aqua)]($style)'

[git_state]
style = "bg:aqua fg:bg1"
format = '[[ \($state( $progress_current/$progress_total)\) ](fg:bg1 bg:aqua)]($style)'

[python]
symbol = ""
style = "bg:blue fg:bg1"
format = '[[ $symbol $virtualenv ](fg:bg1 bg:blue)]($style)'

[kubernetes]
disabled = false
style = "bg:bg3 fg:fg"
format = '[[ ☸ $context(:$namespace) ](fg:fg bg:bg3)]($style)'
detect_folders = ['clusters', 'distributions']
detect_files = [
  'Chart.yaml',
  'helmfile.yaml',
  'values-dev.yaml',
  'values-prod.yaml',
]

[cmd_duration]
style = "bg:bg1 fg:fg"
format = '[[  $duration ](fg:fg bg:bg1)]($style)'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[palettes.everforest]
bg1 = "#2e383c"
bg3 = "#414b50"
fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
